name: in_app_remote
description: "A lightweight Flutter package for remote in-app configuration and testing. It allows developers to fetch, update, and validate app settings dynamically without requiring a full app release. Built-in support for unit tests and widget tests ensures configurations behave as expected across different environments."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/in_app_remote

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: